// Generated by Celest. This file should not be modified manually, but
// it can be checked into version control.
// ignore_for_file: type=lint, unused_local_variable, unnecessary_cast, unnecessary_import

library;

import 'package:celest/celest.dart';

abstract final class apis {
  static const links = CloudApi(name: r'links');
}

abstract final class functions {
  static const linksCreateLink = CloudFunction(
    api: r'links',
    functionName: r'createLink',
  );

  static const linksDeleteLink = CloudFunction(
    api: r'links',
    functionName: r'deleteLink',
  );

  static const linksGetLink = CloudFunction(
    api: r'links',
    functionName: r'getLink',
  );
}

abstract final class env {
  static const supabaseUrl = EnvironmentVariable(name: r'supabaseUrl');

  static const supabaseKey = EnvironmentVariable(name: r'supabaseKey');
}
